client_domain: sugarfunge.com
services:
  - { 'name': 'auth' ,
      'ip': '127.0.0.1',
      'port': '8080',
      'generic_headers': 'false'
    }
  - { 'name': 'api' ,
      'ip': '127.0.0.1',
      'port': '4000',
      'frame_options': 'true',
      'csp_header': "default-src 'none'; frame-ancestors 'none';"
    }
  - { 'name': 'node' ,
      'ip': '127.0.0.1',
      'port': '9944',
      'frame_options': 'true',
      'csp_header': "default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none';"
    }
  - { 'name': 'status' ,
      'ip': '127.0.0.1',
      'port': '8000',
      'frame_options': 'true',
      'csp_header': "default-src https: wss: 'unsafe-eval' 'unsafe-inline'; object-src 'none'; font-src 'self' data: https://fonts.gstatic.com;"
    }
  - { 'name': 'explorer' ,
      'ip': '127.0.0.1',
      'port': '3000',
      'frame_options': 'true',
      'csp_header': "default-src https: wss: 'unsafe-eval' 'unsafe-inline'; object-src 'none'; img-src 'self' data:; font-src 'self' data: https://fonts.gstatic.com;"
    }
  - { 'name': 'ipfs' ,
      'ip': '127.0.0.1',
      'port': '8001',
      'frame_options': 'true',
      'csp_header': "default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none';"
    }
  - { 'name': 'webui.ipfs' ,
      'ip': '127.0.0.1',
      'port': '5001',
      'frame_options': 'true',
      'csp_header': "default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none';"
    }
