version: "3.3"

services:
  tf:
    container_name: Terraform
    image: hashicorp/terraform:1.2.3
    working_dir: /sugarfungetf
    volumes:
        - .:/sugarfungetf
        - /home/${USERNAME}/.ssh:/ssh
